apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather
spec:
  type: LoadBalancer
  selector:
    app: weather
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
